<?xml version="1.0" encoding="utf-8"?><Database Name="AgendaDB" Class="AgendaLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=X\SQLEXPRESS;Initial Catalog=AgendaDB;Integrated Security=True" SettingsObjectName="Datos.Properties.Settings" SettingsPropertyName="AgendaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ContactosTB" Member="ContactosTB">
    <Type Name="ContactosTB">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>